version: "11.1"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    env_file:
     - '.env'
    ports:
     - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
     
volumes:
   grafana_storage: {}
